services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: AmirRzn
      POSTGRES_PASSWORD: Amir1380
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://AmirRzn:Amir1380@db:5432/tasks_db   
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

volumes:
  postgres_data: 